const ApiName=[
    {
        shape:"pear",
        price:"55,40",
        carat:"1.00"
    },
    {
        shape:"Oval",
        price:"6000",
        carat:"2.00"
    },
    {
        shape:"Oval",
        price:"3000",
        carat:"2.32",
    },
    {
        shape:"Oval",
        price:"4000",
        carat:"0.177"
    },
    {
        shape:"Oval",
        price:"10000",
        carat:"2.31"
    },
    {
        shape:"Oval",
        price:"50000",
        carat:"1.43"
    },
    {
        shape:"Oval",
        price:"4500",
        carat:"1.65"
    },
    {
        shape:"Oval",
        price:"34000",
        carat:"0.67"
    },
    {
        shape:"Oval",
        price:"12000",
        carat:"1.32"
    },
    {
        shape:"Oval",
        price:"2340",
        carat:"0.43"
    },
    {
        shape:"Oval",
        price:"6543",
        carat:"2.46"
    },
    {
        shape:"Oval",
        price:"1211",
        carat:"4.32"
    },
    {
        shape:"Oval",
        price:"7884",
        carat:"5.31"
    },
    {
        shape:"Oval",
        price:"2323",
        carat:"2.3"
    },
    {
        shape:"Oval",
        price:"102020",
        carat:"2.1"
    },
    {
        shape:"Oval",
        price:"65431",
        carat:"1.54"
    },
    {
        shape:"Oval",
        price:"65432",
        carat:"2.4"
    },
    {
        shape:"Oval",
        price:"1323",
        carat:"3.32"
    },
    {
        shape:"cushion",
        price:"54321",
        carat:"1.45"
    },
    {
        shape:"cushion",
        price:"76544",
        carat:"2.56"
    },
    {
        shape:"cushion",
        price:"64342",
        carat:"1.44"
    },
    {
        shape:"cushion",
        price:"3231",
        carat:"1.2"
    },
    {
        shape:"cushion",
        price:"2312",
        carat:"2.09"
    },
    {
        shape:"cushion",
        price:"64544",
        carat:"2.43"
    },
    {
        shape:"cushion",
        price:"56547",
        carat:"2.21"
    },
    {
        shape:"cushion",
        price:"7545",
        carat:"2.1"
    },
    {
        shape:"cushion",
        price:"68976",
        carat:"2.45"
    },
    {
        shape:"cushion",
        price:"9765",
        carat:"2.98"
    },
    {
        shape:"cushion",
        price:"6543",
        carat:"2.76"
    },
    {
        shape:"emrald",
        price:"12323",
        carat:"2.75"
    },
    {
        shape:"emrald",
        price:"97655",
        carat:"2.12"
    },
    {
        shape:"emrald",
        price:"53434",
        carat:"2.09"
    },
    {
        shape:"emrald",
        price:"5465",
        carat:"2.64"
    },
    {
        shape:"emrald",
        price:"34322",
        carat:"2.32"
    },
    {
        shape:"emrald",
        price:"67876",
        carat:"2.12"
    },
    {
        shape:"emrald",
        price:"74453",
        carat:"1.45"
    },
    {
        shape:"emrald",
        price:"543532",
        carat:"1.54"
    },
    {
        shape:"radiant",
        price:"23232",
        carat:"1.21"
    },
    {
        shape:"radiant",
        price:"986756",
        carat:"3.34"
    },
    {
        shape:"radiant",
        price:"785645",
        carat:"1.32"
    },
    {
        shape:"radiant",
        price:"75644",
        carat:"1.76"
    },
    {
        shape:"radiant",
        price:"64432",
        carat:"1.54"
    },
    {
        shape:"radiant",
        price:"2321",
        carat:"2.77"
    },
    {
        shape:"heart",
        price:"8675",
        carat:"2.87"
    },
    {
        shape:"heart",
        price:"7564",
        carat:"2.87"
    },
    {
        shape:"heart",
        price:"67564",
        carat:"2.12"
    },
    {
        shape:"heart",
        price:"23232",
        carat:"1.87"
    },
    {
        shape:"heart",
        price:"67576",
        carat:"1.43"
    },
    {
        shape:"marquise",
        price:"65764",
        carat:"1.53"
    },
    {
        shape:"marquise",
        price:"32423",
        carat:"1.87"
    },
    {
        shape:"marquise",
        price:"32323",
        carat:"3.31"
    },
    {
        shape:"marquise",
        price:"64534",
        carat:"1.43"
    },
    {
        shape:"marquise",
        price:"54354",
        carat:"2.43"
    },
    {
        shape:"marquise",
        price:"43523",
        carat:"2.43"
    },
    {
        shape:"princess",
        price:"65445",
        carat:"2.46"
    },
    {
        shape:"princess",
        price:"34322",
        carat:"2.65"
    },
    {
        shape:"princess",
        price:"12112",
        carat:"1.43"
    },
    {
        shape:"princess",
        price:"54657",
        carat:"1.54"
    },
    {
        shape:"princess",
        price:"76564",
        carat:"1.54"
    },
    {
        shape:"princess",
        price:"23234",
        carat:"1.87"
    },
]

export default ApiName ;